// UK postcode areas → main town/city, region/nation and approximate catchment population.
// Populations are approximate postcode-area catchment figures (ONS/NISRA mid-2021 based, thousands rounded)
// and are used only to compare relative market penetration, not for reporting official statistics.

export interface PostcodeArea {
  area: string;
  town: string;
  region: string;
  nation: 'England' | 'Scotland' | 'Wales' | 'Northern Ireland';
  population: number; // people in the postcode area catchment
}

export const UK_POSTCODE_AREAS: PostcodeArea[] = [
  { area: 'AB', town: 'Aberdeen', region: 'North East Scotland', nation: 'Scotland', population: 500000 },
  { area: 'AL', town: 'St Albans', region: 'Hertfordshire', nation: 'England', population: 340000 },
  { area: 'B', town: 'Birmingham', region: 'West Midlands', nation: 'England', population: 2100000 },
  { area: 'BA', town: 'Bath', region: 'Somerset', nation: 'England', population: 470000 },
  { area: 'BB', town: 'Blackburn', region: 'Lancashire', nation: 'England', population: 530000 },
  { area: 'BD', town: 'Bradford', region: 'West Yorkshire', nation: 'England', population: 720000 },
  { area: 'BH', town: 'Bournemouth', region: 'Dorset', nation: 'England', population: 600000 },
  { area: 'BL', town: 'Bolton', region: 'Greater Manchester', nation: 'England', population: 500000 },
  { area: 'BN', town: 'Brighton', region: 'East Sussex', nation: 'England', population: 800000 },
  { area: 'BR', town: 'Bromley', region: 'South East London', nation: 'England', population: 340000 },
  { area: 'BS', town: 'Bristol', region: 'South West', nation: 'England', population: 900000 },
  { area: 'BT', town: 'Belfast (all NI)', region: 'Northern Ireland', nation: 'Northern Ireland', population: 1900000 },
  { area: 'CA', town: 'Carlisle', region: 'Cumbria', nation: 'England', population: 340000 },
  { area: 'CB', town: 'Cambridge', region: 'Cambridgeshire', nation: 'England', population: 500000 },
  { area: 'CF', town: 'Cardiff', region: 'South Wales', nation: 'Wales', population: 900000 },
  { area: 'CH', town: 'Chester', region: 'Cheshire / Wirral', nation: 'England', population: 620000 },
  { area: 'CM', town: 'Chelmsford', region: 'Essex', nation: 'England', population: 750000 },
  { area: 'CO', town: 'Colchester', region: 'Essex', nation: 'England', population: 420000 },
  { area: 'CR', town: 'Croydon', region: 'South London', nation: 'England', population: 480000 },
  { area: 'CT', town: 'Canterbury', region: 'Kent', nation: 'England', population: 550000 },
  { area: 'CV', town: 'Coventry', region: 'Warwickshire', nation: 'England', population: 890000 },
  { area: 'CW', town: 'Crewe', region: 'Cheshire', nation: 'England', population: 300000 },
  { area: 'DA', town: 'Dartford', region: 'Kent', nation: 'England', population: 420000 },
  { area: 'DD', town: 'Dundee', region: 'Tayside', nation: 'Scotland', population: 300000 },
  { area: 'DE', town: 'Derby', region: 'Derbyshire', nation: 'England', population: 700000 },
  { area: 'DG', town: 'Dumfries', region: 'Dumfries & Galloway', nation: 'Scotland', population: 150000 },
  { area: 'DH', town: 'Durham', region: 'County Durham', nation: 'England', population: 330000 },
  { area: 'DL', town: 'Darlington', region: 'Tees Valley', nation: 'England', population: 380000 },
  { area: 'DN', town: 'Doncaster', region: 'South Yorkshire', nation: 'England', population: 800000 },
  { area: 'DT', town: 'Dorchester', region: 'Dorset', nation: 'England', population: 220000 },
  { area: 'DY', town: 'Dudley', region: 'West Midlands', nation: 'England', population: 450000 },
  { area: 'E', town: 'East London', region: 'London', nation: 'England', population: 1000000 },
  { area: 'EC', town: 'City of London', region: 'London', nation: 'England', population: 90000 },
  { area: 'EH', town: 'Edinburgh', region: 'Lothian', nation: 'Scotland', population: 950000 },
  { area: 'EN', town: 'Enfield', region: 'North London', nation: 'England', population: 400000 },
  { area: 'EX', town: 'Exeter', region: 'Devon', nation: 'England', population: 480000 },
  { area: 'FK', town: 'Falkirk', region: 'Central Scotland', nation: 'Scotland', population: 260000 },
  { area: 'FY', town: 'Blackpool', region: 'Lancashire', nation: 'England', population: 330000 },
  { area: 'G', town: 'Glasgow', region: 'Greater Glasgow', nation: 'Scotland', population: 1200000 },
  { area: 'GL', town: 'Gloucester', region: 'Gloucestershire', nation: 'England', population: 550000 },
  { area: 'GU', town: 'Guildford', region: 'Surrey / Hampshire', nation: 'England', population: 900000 },
  { area: 'HA', town: 'Harrow', region: 'North West London', nation: 'England', population: 450000 },
  { area: 'HD', town: 'Huddersfield', region: 'West Yorkshire', nation: 'England', population: 260000 },
  { area: 'HG', town: 'Harrogate', region: 'North Yorkshire', nation: 'England', population: 160000 },
  { area: 'HP', town: 'Hemel Hempstead', region: 'Buckinghamshire', nation: 'England', population: 600000 },
  { area: 'HR', town: 'Hereford', region: 'Herefordshire', nation: 'England', population: 190000 },
  { area: 'HS', town: 'Outer Hebrides', region: 'Highlands & Islands', nation: 'Scotland', population: 27000 },
  { area: 'HU', town: 'Hull', region: 'East Yorkshire', nation: 'England', population: 570000 },
  { area: 'HX', town: 'Halifax', region: 'West Yorkshire', nation: 'England', population: 160000 },
  { area: 'IG', town: 'Ilford', region: 'East London / Essex', nation: 'England', population: 380000 },
  { area: 'IP', town: 'Ipswich', region: 'Suffolk', nation: 'England', population: 540000 },
  { area: 'IV', town: 'Inverness', region: 'Highlands', nation: 'Scotland', population: 220000 },
  { area: 'KA', town: 'Kilmarnock', region: 'Ayrshire', nation: 'Scotland', population: 370000 },
  { area: 'KT', town: 'Kingston upon Thames', region: 'Surrey', nation: 'England', population: 620000 },
  { area: 'KW', town: 'Kirkwall / Wick', region: 'Highlands & Orkney', nation: 'Scotland', population: 60000 },
  { area: 'KY', town: 'Kirkcaldy', region: 'Fife', nation: 'Scotland', population: 340000 },
  { area: 'L', town: 'Liverpool', region: 'Merseyside', nation: 'England', population: 1100000 },
  { area: 'LA', town: 'Lancaster', region: 'Lancashire / Cumbria', nation: 'England', population: 340000 },
  { area: 'LD', town: 'Llandrindod Wells', region: 'Mid Wales', nation: 'Wales', population: 50000 },
  { area: 'LE', town: 'Leicester', region: 'Leicestershire', nation: 'England', population: 900000 },
  { area: 'LL', town: 'Llandudno', region: 'North Wales', nation: 'Wales', population: 500000 },
  { area: 'LN', town: 'Lincoln', region: 'Lincolnshire', nation: 'England', population: 330000 },
  { area: 'LS', town: 'Leeds', region: 'West Yorkshire', nation: 'England', population: 950000 },
  { area: 'LU', town: 'Luton', region: 'Bedfordshire', nation: 'England', population: 400000 },
  { area: 'M', town: 'Manchester', region: 'Greater Manchester', nation: 'England', population: 1500000 },
  { area: 'ME', town: 'Medway / Maidstone', region: 'Kent', nation: 'England', population: 700000 },
  { area: 'MK', town: 'Milton Keynes', region: 'Buckinghamshire', nation: 'England', population: 600000 },
  { area: 'ML', town: 'Motherwell', region: 'Lanarkshire', nation: 'Scotland', population: 400000 },
  { area: 'N', town: 'North London', region: 'London', nation: 'England', population: 800000 },
  { area: 'NE', town: 'Newcastle upon Tyne', region: 'Tyne & Wear', nation: 'England', population: 1200000 },
  { area: 'NG', town: 'Nottingham', region: 'Nottinghamshire', nation: 'England', population: 1000000 },
  { area: 'NN', town: 'Northampton', region: 'Northamptonshire', nation: 'England', population: 620000 },
  { area: 'NP', town: 'Newport', region: 'South East Wales', nation: 'Wales', population: 430000 },
  { area: 'NR', town: 'Norwich', region: 'Norfolk', nation: 'England', population: 720000 },
  { area: 'NW', town: 'North West London', region: 'London', nation: 'England', population: 700000 },
  { area: 'OL', town: 'Oldham', region: 'Greater Manchester', nation: 'England', population: 460000 },
  { area: 'OX', town: 'Oxford', region: 'Oxfordshire', nation: 'England', population: 620000 },
  { area: 'PA', town: 'Paisley', region: 'Renfrewshire / Argyll', nation: 'Scotland', population: 400000 },
  { area: 'PE', town: 'Peterborough', region: 'Cambridgeshire', nation: 'England', population: 900000 },
  { area: 'PH', town: 'Perth', region: 'Perthshire / Highlands', nation: 'Scotland', population: 240000 },
  { area: 'PL', town: 'Plymouth', region: 'Devon / Cornwall', nation: 'England', population: 560000 },
  { area: 'PO', town: 'Portsmouth', region: 'Hampshire / IoW', nation: 'England', population: 800000 },
  { area: 'PR', town: 'Preston', region: 'Lancashire', nation: 'England', population: 550000 },
  { area: 'RG', town: 'Reading', region: 'Berkshire', nation: 'England', population: 800000 },
  { area: 'RH', town: 'Redhill / Crawley', region: 'Surrey / Sussex', nation: 'England', population: 550000 },
  { area: 'RM', town: 'Romford', region: 'East London / Essex', nation: 'England', population: 480000 },
  { area: 'S', town: 'Sheffield', region: 'South Yorkshire', nation: 'England', population: 1100000 },
  { area: 'SA', town: 'Swansea', region: 'South West Wales', nation: 'Wales', population: 700000 },
  { area: 'SE', town: 'South East London', region: 'London', nation: 'England', population: 900000 },
  { area: 'SG', town: 'Stevenage', region: 'Hertfordshire', nation: 'England', population: 400000 },
  { area: 'SK', town: 'Stockport', region: 'Greater Manchester / Cheshire', nation: 'England', population: 600000 },
  { area: 'SL', town: 'Slough', region: 'Berkshire', nation: 'England', population: 400000 },
  { area: 'SM', town: 'Sutton', region: 'South London', nation: 'England', population: 260000 },
  { area: 'SN', town: 'Swindon', region: 'Wiltshire', nation: 'England', population: 480000 },
  { area: 'SO', town: 'Southampton', region: 'Hampshire', nation: 'England', population: 750000 },
  { area: 'SP', town: 'Salisbury', region: 'Wiltshire', nation: 'England', population: 260000 },
  { area: 'SR', town: 'Sunderland', region: 'Tyne & Wear', nation: 'England', population: 330000 },
  { area: 'SS', town: 'Southend-on-Sea', region: 'Essex', nation: 'England', population: 600000 },
  { area: 'ST', town: 'Stoke-on-Trent', region: 'Staffordshire', nation: 'England', population: 620000 },
  { area: 'SW', town: 'South West London', region: 'London', nation: 'England', population: 900000 },
  { area: 'SY', town: 'Shrewsbury', region: 'Shropshire / Mid Wales', nation: 'England', population: 350000 },
  { area: 'TA', town: 'Taunton', region: 'Somerset', nation: 'England', population: 300000 },
  { area: 'TD', town: 'Galashiels', region: 'Scottish Borders', nation: 'Scotland', population: 130000 },
  { area: 'TF', town: 'Telford', region: 'Shropshire', nation: 'England', population: 190000 },
  { area: 'TN', town: 'Tonbridge', region: 'Kent / Sussex', nation: 'England', population: 620000 },
  { area: 'TQ', town: 'Torquay', region: 'Devon', nation: 'England', population: 280000 },
  { area: 'TR', town: 'Truro', region: 'Cornwall', nation: 'England', population: 350000 },
  { area: 'TS', town: 'Middlesbrough', region: 'Tees Valley', nation: 'England', population: 620000 },
  { area: 'TW', town: 'Twickenham', region: 'West London', nation: 'England', population: 460000 },
  { area: 'UB', town: 'Uxbridge', region: 'West London', nation: 'England', population: 400000 },
  { area: 'W', town: 'West London', region: 'London', nation: 'England', population: 600000 },
  { area: 'WA', town: 'Warrington', region: 'Cheshire', nation: 'England', population: 700000 },
  { area: 'WC', town: 'Central London', region: 'London', nation: 'England', population: 60000 },
  { area: 'WD', town: 'Watford', region: 'Hertfordshire', nation: 'England', population: 350000 },
  { area: 'WF', town: 'Wakefield', region: 'West Yorkshire', nation: 'England', population: 500000 },
  { area: 'WN', town: 'Wigan', region: 'Greater Manchester', nation: 'England', population: 330000 },
  { area: 'WR', town: 'Worcester', region: 'Worcestershire', nation: 'England', population: 330000 },
  { area: 'WS', town: 'Walsall', region: 'West Midlands', nation: 'England', population: 450000 },
  { area: 'WV', town: 'Wolverhampton', region: 'West Midlands', nation: 'England', population: 450000 },
  { area: 'YO', town: 'York', region: 'North Yorkshire', nation: 'England', population: 550000 },
  { area: 'ZE', town: 'Lerwick (Shetland)', region: 'Highlands & Islands', nation: 'Scotland', population: 23000 },
  { area: 'IM', town: 'Isle of Man', region: 'Crown Dependency', nation: 'England', population: 84000 },
  { area: 'JE', town: 'Jersey', region: 'Channel Islands', nation: 'England', population: 103000 },
  { area: 'GY', town: 'Guernsey', region: 'Channel Islands', nation: 'England', population: 64000 },
];

export const POSTCODE_AREA_MAP: Record<string, PostcodeArea> = UK_POSTCODE_AREAS.reduce(
  (acc, a) => {
    acc[a.area] = a;
    return acc;
  },
  {} as Record<string, PostcodeArea>
);

export const NATIONS = ['England', 'Scotland', 'Wales', 'Northern Ireland'] as const;
