// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzauvmzsjchjfozahdxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6YXV2bXpzamNoamZvemFoZHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwOTMyNTEsImV4cCI6MjA4MDY2OTI1MX0.MZ3q7tzW27WP2xEoM9BPN4BDJ4J14sEFiNev2NY6ons";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});